### ISSUE TITLE
Can't enable x, y coordinate as a trait.

### ISSUE THREAD

**Issue by rohanrajpal** [mwcraig/ipyevents#26]
I get an AttributeError when I try to access the xy trait from no_drag. 
This happened while following [the demo notebook](https://github.com/mwcraig/ipyevents/blob/master/doc/Widget%20DOM%20Events.ipynb).

The full error is
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-75ef162e19fd> in <module>()
----> 1 no_drag.xy

AttributeError: 'Event' object has no attribute 'xy'
```

**Comment by mwcraig** [comment]
Thanks for the report, I'll get this fixed today

**Comment by mwcraig** [comment]
@rohanrajpal version 0.3.0 is now on pypi and will soon be available as a conda package on conda-forge.
