### ISSUE TITLE
Up/down arrow key events captured by browser

### ISSUE THREAD

**Issue by pllim** [mwcraig/ipyevents#27]
UPDATE: I also see this on RHEL 7 64-bit using Firefox 52.8.0.

Discovered during Scipy 2018. While panning using Ginga viewer with `ipyevents`, the up/down arrows where somehow captured by the browser. This resulted in notebook jumping up and down, instead of panning up and down. I was running eteq/astrowidgets#1 on Windows 7 64-bit:

* Python 3.6.5
* Numpy 1.14.5
* Astropy 3.1.dev22186
* Ginga 2.7.1.dev1944
* ipyevents 0.3.1
* freetype 2.8.1
* aggdraw from https://github.com/ejeschke/aggdraw/tree/vectorized-drawing
* jupyter 1.0.0
* jupyter_client 5.2.3
* jupyter_console 5.2.0
* jupyter_core 4.4.0
* jupyterlab 0.32.1
* jupyterlab_launcher 0.10.5

I *think* I see the image did pan like a few pixels but I am not sure because the browser was also unintentionally scrolling at the same time.

**Comment by mwcraig** [comment]
@pllim  -- I *think* this is fixed in ipyevents 0.4.0.....I was able to pan in the ginga widget with shift+arrow key without scrolling the browser, at least.

**Comment by pllim** [comment]
Thanks, Matt. I'll follow up when I get the chance.
