### ISSUE TITLE
plot window bug

### ISSUE THREAD

**Issue by SaOgaz** [mwcraig/ipyevents#37]
Hey @mwcraig, logging the bug I came across during our JWST hackday.  It's kind of hard to describe, but basically if I have an active clicked on cell in the notebook, and I then go mouse onto and off of a plot window, the notebook flashes back to the active cell.

The notebook I was working on can be found here: https://github.com/SaOgaz/dat_pyinthesky/blob/mos_notebook/jwst_nb_viz/mos/MOS_spec_xgal_fields.ipynb

Video clip of bug can be found here: https://stsci.box.com/s/9m7py2u4wrtqgop2jifbvzfpw859itxn

Including my whole conda list here, sorry for the cruft. Not sure what libraries are dependencies for this stuff.

My current versions of things are:
 Name                    Version                   Build  Channel
aggdraw                   1.3.9                     <pip>
appnope                   0.1.0                    py37_0  
astropy                   3.1.1            py37h1de35cc_0  
astrowidgets              0.1.0.dev104              <pip>
atomicwrites              1.3.0                      py_0  
attrs                     18.2.0           py37h28b3542_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              hc4e6be7_4  
certifi                   2018.11.29               py37_0  
cloudpickle               0.7.0                      py_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.5           py37h0a44026_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dask-core                 1.1.1                      py_0  
dbus                      1.13.6               h90a0687_0  
decorator                 4.3.2                    py37_0  
entrypoints               0.3                      py37_0  
expat                     2.2.6                h0a44026_0  
ffmpeg                    4.0                  h01ea3c9_0  
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
gettext                   0.19.8.1             h15daf44_3  
ginga                     2.7.2                    py37_0    http://ssb.stsci.edu/astroconda
glib                      2.56.2               hd9629dc_0  
graphite2                 1.3.13               h2098e52_0  
harfbuzz                  1.8.8                hb8d4a28_0  
hdf5                      1.10.2               hfa1e0ec_1  
icu                       58.2                 h4b95b61_1  
imageio                   2.4.1                    py37_0  
imexam                    0.8.1                    py37_0    http://ssb.stsci.edu/astroconda
intel-openmp              2019.1                      144  
ipyevents                 0.4.0                     <pip>
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.2.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jasper                    2.0.14               h636a363_1  
jedi                      0.13.2                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
kiwisolver                1.0.1            py37h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libopencv                 3.4.2                h7c891bd_1  
libopus                   1.3                  h1de35cc_0  
libpng                    1.6.36               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.0.10               hcb84e12_2  
libvpx                    1.7.0                h378b8a2_0  
libxml2                   2.9.9                hab757c2_0  
markupsafe                1.1.0            py37h1de35cc_0  
matplotlib                3.0.2            py37h54f8f79_0  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
more-itertools            5.0.0                    py37_0  
nbconvert                 5.3.1                    py37_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.2                      py37_1  
notebook                  5.7.4                    py37_0  
numpy                     1.15.4           py37hacdab7b_0  
numpy-base                1.15.4           py37h6575580_0  
olefile                   0.46                     py37_0  
opencv                    3.4.2            py37h6fd60c2_1  
openssl                   1.1.1a               h1de35cc_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.2                    py37_0  
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                    py37_0  
photutils                 0.6                      py37_0    http://ssb.stsci.edu/astroconda
pickleshare               0.7.5                    py37_0  
pillow                    5.4.1            py37hb68e598_0  
pip                       19.0.1                   py37_0  
pixman                    0.36.0               h1de35cc_0  
pluggy                    0.8.1                    py37_0  
prometheus_client         0.5.0                    py37_0  
prompt_toolkit            2.0.8                      py_0  
psutil                    5.5.0            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.7.0                    py37_0  
py-opencv                 3.4.2            py37h7c891bd_1  
pygments                  2.3.1                    py37_0  
pyparsing                 2.3.1                    py37_0  
pyqt                      5.9.2            py37h655552a_2  
pytest                    4.2.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.2.0                    py37_0  
pytest-openfiles          0.3.2                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.2                haf84260_0  
python-dateutil           2.7.5                    py37_0  
pytz                      2018.9                   py37_0  
pywavelets                1.0.1            py37h1d22016_0  
pyzmq                     17.1.2           py37h0a44026_2  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.6.0                      py_0  
readline                  7.0                  h1de35cc_5  
scikit-image              0.14.1           py37h0a44026_0  
scikit-learn              0.20.2           py37h27c97d8_0  
scipy                     1.2.0            py37h1410ff5_0  
send2trash                1.5.0                    py37_0  
setuptools                40.8.0                   py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
sqlite                    3.26.0               ha441bb4_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1.1            py37h1de35cc_0  
traitlets                 4.3.2                    py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.32.3                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
xz                        5.2.4                h1de35cc_4  
zeromq                    4.3.1                h0a44026_3  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by mwcraig** [comment]
Thanks for the video...that behavior is very irritating 😬 , to say the least....

Which browser/browser version are you using?

**Comment by SaOgaz** [comment]
Google chrome, Version 72.0.3626.109 (Official Build) (64-bit). 👍

**Comment by pllim** [comment]
I see the same thing on Chrome and Windows 10.

**Comment by eteq** [comment]
If it helps any, I did *not* see this bug in one of my older environments with the following:

notebook 5.7.2
ipyevents 0.3.1
ginga 2.7.0
ipywidgets 7.3.1

Chrome 71.0.3578.98 (Official Build) (64-bit)
mac OSX 10.11.6

**Comment by mwcraig** [comment]
Fixed this in 074075e89fbff8fef3176d20d02eac5435e8a351, am about to do a new release.

**Comment by pllim** [comment]
Just for the record, @mwcraig , what would be the release number with this fix for those who see this issue in the future? 0.4.1?
