### ISSUE TITLE
Add link to documentation in README

### ISSUE THREAD

**Issue by pbugnion** [mwcraig/ipyevents#4]
ipyevents is really great. I think the widgets community could really benefit from using it.

It has great documentation, but finding it isn't completely obvious. Maybe we could add a link in the README to the `docs/` directory?

Happy to implement this if you think it's a good idea.

**Comment by pbugnion** [comment]
Never mind -- I completely missed the `doc/` directory. Maybe the only thing this needs is a reference to the `doc/` page in the README.

**Comment by mwcraig** [comment]
Please do go ahead and implement -- also let me know if you are interested in being added as a maintainer. My thought was to transfer several of the comments from the original ipywidgets PR over to hear as issues, tag the most critical as 0.1, get those fixed, then announce the release.

I'll be tied up much of this week, much more open the following one.

**Comment by pbugnion** [comment]
I've submitted a PR.

> let me know if you are interested in being added as a maintainer

I think this is a really useful addition to the widgets ecosystem, so I'd definitely like to contribute more!

> My thought was to transfer several of the comments from the original ipywidgets PR over to hear as issues, tag the most critical as 0.1, get those fixed, then announce the release

Sounds like a good plan.

**Comment by mwcraig** [comment]
Closed by #5
