### ISSUE TITLE
Spacebar does not activate Ginga's meta mode anymore

### ISSUE THREAD

**Issue by pllim** [mwcraig/ipyevents#40]
This is a follow up of the fix made for #37. The "jumping" is gone but I cannot use spacebar to enter Ginga viewer's "meta [L]" mode anymore, as a result, `astrowidgets.ImageWidget` workflow is broken. This is using `ipyevents` 0.4.1.

cc @ejeschke and @eteq

**Comment by pllim** [comment]
Actually, this might be more serious than what I posted above. I think all keyboard key bindings for Ginga viewer are gone. I cannot use numeric keys to change zoom either.

**Comment by ejeschke** [comment]
Can you open the browser javascript console to see if there are any errors showing up there when you type into the widget?

**Comment by pllim** [comment]
I couldn't figure out how to save the log into plain text, so here is a screenshot.

![console_errors](https://user-images.githubusercontent.com/2090236/53581753-2cff6880-3b4c-11e9-9438-451eeec20f23.jpg)

**Comment by pllim** [comment]
Actually, when I `pip install ipyevents==0.4.0` into my `conda` environment, I get this same problem too! But it works when I do a `conda install ipyevents`. :confused:

**Comment by mwcraig** [comment]
Hi,

I'll try to take a look today (recovering from a bad cold so not sure hoe
much progress I'll make). I made a couple of changes in 0.4.1 that might
have led to this.

Can you please send the output from a terminal of `jupyter nbextension list`

After that, can you try these steps after pip installing:

```
jupyter nbextension install --sys-prefix ipyevents
jupyter nbextension enable --sys-prefix ipyevents
```

If you are running it in lab then you have to: `jupyter labextensino
install ipyevents`

Matt

**Comment by pllim** [comment]
```
$ jupyter nbextension list
      - Validating: ok
      - Validating: ok
Known nbextensions:
  config dir: C:\...\Miniconda3\envs\py37\etc\jupyter\nbconfig
    notebook section
      ipyevents/extension enabled
      jupyter-js-widgets/extension enabled
```

Then I `conda uninstall ipyevents` followed by `pip install ipyevents` to pick up 0.4.1 (again). But `jupyter nbextension install --sys-prefix ipyevents` fails.

```
Traceback (most recent call last):
  File "C:\...\Miniconda3\envs\py37\Scripts\jupyter-nbextension-script.py", line 11, in <module>
    load_entry_point('notebook==5.7.4', 'console_scripts', 'jupyter-nbextension')()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 716, in start
    self.install_extensions()
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 695, in install_extensions
    **kwargs
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 199, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 1043, in _maybe_copy
    if _should_copy(src, dest, logger=logger):
  File "C:\...\Miniconda3\envs\py37\lib\site-packages\notebook\nbextensions.py", line 1019, in _should_copy
    if os.stat(src).st_mtime - os.stat(dest).st_mtime > 1e-6:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'ipyevents'
```

**Comment by mwcraig** [comment]
My bad, I left out a an option:

`jupyter nbextension install --py --sys-prefix ipyevents`

I don't think that will fix it though, since the ipyevents extension is already listed as installed and enabled.

**Comment by mwcraig** [comment]
Does the demo notebook for ipyevents work for you?

**Comment by pllim** [comment]
I think `jupyter nbextension install --py --sys-prefix ipyevents` fixed it. For lab, I also ran `jupyter labextension install ipyevents`. Now it works. Magic. Thanks!

**Comment by ejeschke** [comment]
Seems like I've seen two or three different incantations for the `jupyter nbextension install` command now (over the years), and it is a little difficult to remember which one is correct.  @pllim, maybe we should double check that we have an up-to-date note somewhere in the ginga install docs that if you want to use the `jupyterw` version this is what you have to do.

**Comment by pllim** [comment]
The instructions in `ginga/examples/jupyter-notebook/Jupyter Widget Ideas.ipynb` said:

```
$ pip install ipyevents
$ jupyter nbextension enable --py --sys-prefix ipyevents
```

Is that still correct, @mwcraig ?

**Comment by mwcraig** [comment]
That is never *in*correct, though in some cases it is unnecessary. In notebook v5.3 (or maybe 5.4) they introduced a directory-based scheme for installing notebook extensions that made it possible to install them via setup.py. ipyevents is set up to do that now so it shouldn't (in the future) require any extra steps.

The situation in jupyterlab is a little better because they decided to make all extensions npm packages and to use node/npm to handle the extension installation (instead of iterating through a couple years of custom installation approaches like with notebooks).

**Comment by pllim** [comment]
OK, I'll just leave it be for now then. Thanks for the clarifications!

**Comment by ejeschke** [comment]
Thanks, @mwcraig !
