### ISSUE TITLE
Events not working with jupyterlab 1.0.0

### ISSUE THREAD

**Issue by prabhuramachandran** [mwcraig/ipyevents#44]
Thanks for the really useful package and clean API.
I just tried to run the example in `doc/Widget DOM Events.ipynb` and it works fine on a jupyter notebook but does not work with jupyterlab 1.0.0.  No events are captured on jupyterlab.  This is with ipyevents 0.5.0 from conda-forge and Python 3.7.3.  Thanks.

**Comment by jasongrout** [comment]
To work in JupyterLab 1.0, this line: https://github.com/mwcraig/ipyevents/blob/ff15dd9992391a6d187aaf2582608ba29e312505/js/package.json#L41

needs to be updated to

```
 "@jupyter-widgets/base": "^1.0.4 || ^2",
```

**Comment by prabhuramachandran** [comment]
@jasongrout -- Thanks, I can confirm that this works!

**Comment by prabhuramachandran** [comment]
Sent PR for this in #45
