### ISSUE TITLE
Reset an event

### ISSUE THREAD

**Issue by zerline** [mwcraig/ipyevents#48]
Hi! Thanks for the good work!
In order to suppress all callbacks for a given event, I find no better solution than:

`my_click_event._dom_handlers.callbacks.clear()`

Should we not benefit on a new method like for ex. `Event.reset_callbacks` to do that in a more sensible way?

**Comment by mwcraig** [comment]
That is an excellent idea -- if you are interested in opening a PR that would be great, otherwise I'll try to add something like that in the next week or two.

**Comment by zerline** [comment]
Anyways ..
