### ISSUE TITLE
provide event target information?

### ISSUE THREAD

**Issue by allefeld** [mwcraig/ipyevents#51]
I made a feature suggestion for JupyterLab, https://github.com/jupyterlab/jupyterlab/issues/7873, where I noted that I tried to use `ipyevents` to implement it, and ran into problems.

Could you have a look there and tell me whether you would be interested in extending your package to enable the behavior I need?

Briefly, I need to detect mouse click events, but not by x,y coordinates but by targeted element (or even better, a parent of the target element via `event.target.closest(selector)`).

**Comment by mwcraig** [comment]
@allefeld -- this would be pretty easy to add, I think (a line or two of javascript in ipyevents). 

If you have a bit of time to open a PR to add it that would be great!

**Comment by allefeld** [comment]
I'll try. Can you give me a hint where to look?

**Comment by allefeld** [comment]
see https://github.com/jupyterlab/jupyterlab/issues/7873#issuecomment-586646459

**Comment by mwcraig** [comment]
Closed by #62
