### ISSUE TITLE
Support for JupyterLab 2.0

### ISSUE THREAD

**Issue by itssimon** [mwcraig/ipyevents#52]
JupyterLab has had a major version release (2.0) and unfortunately, it broke a lot of extensions, including ipyevents.

I think all it will take is to follow the instructions in the [extension migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#extension-migration) to make it work again.

**Comment by mwcraig** [comment]
Thanks for the PR!

@itssimon -- any idea if this still works with lab 1.0 or classic notebook?

**Comment by itssimon** [comment]
No, I haven't tested this with JupyterLab 1.0.

**Comment by mwcraig** [comment]
ok, will try it out locally and get this merged today -- would like to make sure it works with classic notebook.....jlab 1 is not so important because jlab is evolving so rapidly.

**Comment by pkgw** [comment]
@mwcraig Would you mind giving us a heads-up when a new release makes it out with this fix? I know that you'll be looking at it too but I'd like to track when the conda-forge package gets updated ...

**Comment by mwcraig** [comment]
It should be out later today; it still works fine the notebook. Haven't tested with jlab 1.0 but don't see a need to.

The only thing I'll change from @itssimon's PR is to bump the version number to 0.8.0 instead of 0.7.1.

**Comment by pkgw** [comment]
FWIW, because of the rename from PhosphorJS to Lumino (presumably there was a good reason, although I have no idea what it is), I'd super doubt that compat with the 1.x JLab series gets maintained.

**Comment by mwcraig** [comment]
> presumably there was a good reason, although I have no idea what it is

See https://github.com/phosphorjs/phosphor

**Comment by slel** [comment]
> See https://github.com/phosphorjs/phosphor

And https://github.com/phosphorjs/phosphorjs.github.io/pull/47

**Comment by pkgw** [comment]
@mwcraig Don't suppose there's anything I can do to help with the release process? I'd like to work on updating pywwt but we're blocked on this.

**Comment by mwcraig** [comment]
Can you give #53 a try on jlab 1 or 2 (your choice)? Whether you can or not I'll do the release later today. I'm pretty sure it works...

**Comment by mwcraig** [comment]
If you want to be added as a maintainer on the repo, let me know. Willing to do that too.
