### ISSUE TITLE
Using ipyevents on a remote (jupyter notebook) server

### ISSUE THREAD

**Issue by kvinicki** [mwcraig/ipyevents#58]
Hi, I tried working with ipyevents widgets in a jupyter notebook that is running on a remote machine, but it doesn't react to DOM events. Can this problem be solved?

**Comment by kvinicki** [comment]
Sorry, it was my bug

**Comment by mwcraig** [comment]
No problem, I'm glad to hear you are using it!

**Comment by olegsinavski** [comment]
@kvinicki what was the bug exactly? I have a similar problem. The following demo doesn't work:
```
from ipywidgets import Label, HTML, HBox, Image, VBox, Box, HBox
from ipyevents import Event 
from IPython.display import display
l = Label('Click or type on me!')
l.layout.border = '2px solid red'

h = HTML('Event info')
d = Event(source=l, watched_events=['click', 'keydown', 'mouseenter', 'touchmove'])

def handle_event(event):
    print('a')
    lines = ['{}: {}'.format(k, v) for k, v in event.items()]
    content = '<br>'.join(lines)
    h.value = content

d.on_dom_event(handle_event)
                            
display(l, h)
```

**Comment by kvinicki** [comment]
If I remember correctly, I installed ipyevents with pip, abd i had to stsrt
jupyter server again in order for it to work

**Comment by mwcraig** [comment]
Feel free to reopen (or to open a new issue) if it isn't working for you @olegsinavski
