### ISSUE TITLE
Support for Mobile Browser

### ISSUE THREAD

**Issue by akaszynski** [mwcraig/ipyevents#59]
First off, great work here!  This is working great for me on the desktop.

Is there any support for mobile browser DOM events?  I'd be happy to contribute if you can point me in the right direction.

**Comment by mwcraig** [comment]
> First off, great work here! This is working great for me on the desktop.

Thanks 😀 

> Is there any support for mobile browser DOM events? I'd be happy to contribute if you can point me in the right direction.

There is not at the moment. I assume you mean these events, right:https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent?

If so, then the places to add them are maybe [here](https://github.com/mwcraig/ipyevents/blob/master/ipyevents/events.py#L103) for adding a new `_supported_touch_events` trait, and then maybe a new list [here](https://github.com/mwcraig/ipyevents/blob/master/src/events.ts#L75) for the events names. There may be some more changes needed in that typescript file depending on how much a touch event differs from other mouse events.

**Comment by mwcraig** [comment]
Closed by #63 -- thanks again for the contribution!
