### ISSUE TITLE
ipyevents@2.0.1 cannot be found on CDN (unpkg.com)

### ISSUE THREAD

**Issue by helincao** [mwcraig/ipyevents#70]
CDN for ipyevents@2.0.1 returns a 404 error. 

Response from CDN:
![image](https://user-images.githubusercontent.com/18755763/126358481-abe4ddcc-99f3-4c30-b79a-6eb53c1a721c.png)

Error message from Chrome console:
![image](https://user-images.githubusercontent.com/18755763/126358319-3542449f-7fcf-48e9-aa0b-a9e68a6fc03a.png)

**Comment by mwcraig** [comment]
@helincao  -- thanks for reporting. Are you using jlab 2 or 3?

**Comment by helincao** [comment]
I did not use jlab. What I did is export an HTML using Leafmap, and hosted as a PyWebIO app. See the app here: https://build.pyweb.io/test/36705/
It works now since we roll back ipyevents to v0.9.0.

**Comment by mwcraig** [comment]
Ah, that is useful to know. In that case I can keep publishing packages on npm. 

I hadn't because it hadn't occurred to me that people might be using it outside the context of jlab (which as of version 3 doesn't pull packages from npm).

I'll let you know when it has been uploaded.

**Comment by helincao** [comment]
Thanks for your support!

**Comment by mwcraig** [comment]
I just pushed the package to npm a couple minutes ago, so 2.0.1 should work for you now -- thanks for sharing how you are using 
 package!
