### ISSUE TITLE
ipyevents not working with VS Code

### ISSUE THREAD

**Issue by giswqs** [mwcraig/ipyevents#87]
Got the following error with VS Code. 

![image](https://github.com/mwcraig/ipyevents/assets/5016453/2b99a50b-f4b6-49a2-ac81-52393ce8eb57)

**Comment by matthew-wtx** [comment]
I'm seeing the same issue

**Comment by mwcraig** [comment]
The underlying issue is that I hadn't published the package to npm, I only published to PyPI. I'll try to get the npm upload done today.

**Comment by mwcraig** [comment]
I think is working now -- can folks give it a try and report back?

If you don't mind also including a brief (like <1 sentence) description of how you are using it that would be great.

**Comment by matthew-wtx** [comment]
@mwcraig I upgraded from 2.0.1 to 2.0.2 and am happy to report that it is working. I'm using ipyevents to build a simple gui in a jupyter notebook that enables clicking on an image to mark points in the image.

**Comment by mwcraig** [comment]
thanks @matthew-wtx!

I'm going to mark this as closed, but feel free to reopen if VS Code stops working
