### ISSUE TITLE
Add rectangular selection and/or lasso selections

### ISSUE THREAD

**Issue by mwcraig** [mwcraig/ipyevents#9]
See https://github.com/jupyter-widgets/ipywidgets/pull/1727#issuecomment-339057129 and following comments

**Comment by pbugnion** [comment]
How did you see this implemented? I think Jason's comment about pushing that interaction to JavaScript and just returning the selection makes sense.

Should this be a new widget -- at the same level as `Event`?

e.g.

```python
class RectangleSelector(CoreWidget):
    
    _selection_style = # define the style of the rectangle selector?

    def _on_selection(self, callback):
        # register handlers
```

**Comment by mwcraig** [comment]
Yeah, that might make more sense. One of the things I like about the current structure is that the JavaScript code is fairly simple. I'd also imagine there is a js library for selections out there.

**Comment by mwcraig** [comment]
Closing, because I agree this is out of scope for ipyevents.
